In [11]:
import pandas as pd
from currency_converter import CurrencyConverter

c = CurrencyConverter()

In [12]:
michelin = 'data/2021CountryContinent.csv'

In [13]:
michelin_df = pd.read_csv(michelin, encoding='ISO-8859-1')

In [14]:
michelin_df.head()

,ï»¿Name,Year,Address,City,Country,Continent,MinPrice,MaxPrice,Currency,Cuisine,Longitude,Latitude,PhoneNumber,Url,WebsiteUrl,Award
0,Les Eleveurs,2021,"Suikerkaai 1a, Halle, 1500, Belgium",Halle,Alemania,Europe,45,145,EUR,"Classic Cuisine, Regional Cuisine",4.237608,50.732199,3.223611e+09,https://guide.michelin.com/en/vlaams-brabant/b...,https://www.les-eleveurs.be/,Bib Gourmand
1,Ibaya,2021,"Carretera General 2, Soldeu, AD100, Andorra",Soldeu,Andorra,Europe,110,145,EUR,"Creative, Modern Cuisine",1.670949,42.575577,3.768707e+08,https://guide.michelin.com/en/canillo/soldeu/r...,http://www.sporthotels.ad,1 MICHELIN Star
2,Celler d'en Toni,2021,"Verge del Pilar 4, Andorra la Vella, AD500, An...",Andorra la Vella,Andorra,Europe,72,72,EUR,Contemporary,1.531772,42.507145,3.768628e+08,https://guide.michelin.com/en/andorra-la-vella...,http://www.cellerdentoni.com,Bib Gourmand
3,Amador,2021,"Grinzinger StraÃe 86, Vienna, 1190, Austria",Vienna,Austria,Europe,265,265,EUR,"Creative, Contemporary",16.358600,48.254011,4.370000e+11,https://guide.michelin.com/en/vienna/wien/rest...,http://www.restaurant-amador.com/,3 MICHELIN Stars
4,SENNS.Restaurant,2021,"SÃ¶llheimerstrasse 16, Salzburg, 5020, Austria",Salzburg,Austria,Europe,85,205,EUR,Creative,13.063449,47.836072,4.370000e+11,https://guide.michelin.com/en/salzburg-region/...,https://www.senns.restaurant/,2 MICHELIN Stars

In [11]:
def currency_convertor(michelin_df,new_currency='USD'):
    try:
        price = michelin_df['MaxPrice']
        curr = michelin_df['Currency']
        new_curr = c.convert(price,curr,new_currency)
        return new_curr
    except:
        print(f'{curr} failed')

michelin_df['max_usd'] = michelin_df.apply(lambda x: currency_convertor(x,new_currency='USD'), axis=1)

nan failed

In [12]:
michelin_df.head()

,Name,Year,Address,Location,Region,Continent,MinPrice,MaxPrice,Currency,Cuisine,Longitude,Latitude,PhoneNumber,Url,WebsiteUrl,Award,max_usd
0,D.O.M.,2021.0,"Rua BarÃ£o de Capanema 549, SÃ£o Paulo, 01411-...",SÃ£o Paulo,NaN,NaN,415,700.0,BRL,Creative,-46.667479,-23.566181,5.510000e+11,https://guide.michelin.com/en/sao-paulo-region...,http://www.domrestaurante.com.br/,2 MICHELIN Stars,139.677179
1,Ryo Gastronomia,2021.0,"Rua Pedroso Alvarenga 665, SÃ£o Paulo, 04531-0...",SÃ£o Paulo,NaN,NaN,160,650.0,BRL,Japanese,-46.676905,-23.581449,5.510000e+11,https://guide.michelin.com/en/sao-paulo-region...,https://www.ryogastronomia.com.br/,2 MICHELIN Stars,129.700238
2,Oteque,2021.0,"Rua Conde de IrajÃ¡ 581, Rio de Janeiro, 22271...",Rio de Janeiro,NaN,NaN,440,440.0,BRL,Modern Cuisine,-43.194424,-22.957470,5.520000e+11,https://guide.michelin.com/en/rio-de-janeiro-r...,https://www.oteque.com/,2 MICHELIN Stars,87.797084
3,Oro,2021.0,"Avenida General San Martin 889, Rio de Janeiro...",Rio de Janeiro,NaN,NaN,445,555.0,BRL,Creative,-43.224710,-22.986010,5.520000e+11,https://guide.michelin.com/en/rio-de-janeiro-r...,http://www.ororestaurante.com.br/,2 MICHELIN Stars,110.744049
4,Kinoshita,2021.0,"Rua Jacques FÃ©lix 405, SÃ£o Paulo, 04509-900,...",SÃ£o Paulo,NaN,NaN,83,383.0,BRL,Japanese,-46.671258,-23.591808,5.510000e+11,https://guide.michelin.com/en/sao-paulo-region...,https://www.restaurantekinoshita.com.br/,1 MICHELIN Star,76.423371

In [13]:
michelin_df.describe()

,Year,MaxPrice,Longitude,Latitude,PhoneNumber,max_usd
count,6375.0,6376.000000,6376.000000,6376.000000,6.268000e+03,6376.000000
mean,2021.0,3806.529172,25.357138,41.260683,3.035166e+11,117.049459
std,0.0,18276.349027,64.651813,11.818583,1.521174e+12,88.678572
min,2021.0,2.000000,-123.719444,-23.638434,4.977184e+07,0.601500
25%,2021.0,60.000000,0.649647,35.726995,3.314261e+10,53.851000
50%,2021.0,120.000000,7.269377,43.761822,3.531653e+10,91.616053
75%,2021.0,265.000000,19.052145,48.847792,8.522579e+10,157.827467
max,2021.0,380000.000000,139.847604,64.144365,4.980000e+13,1402.770525

In [14]:
bins = [0, 300, 600, 900, 1000, 1500]
labels = [1,2,3,4,5]
michelin_df['price'] = pd.cut(michelin_df['max_usd'], bins=bins, labels=labels)
michelin_df.head()

,Name,Year,Address,Location,Region,Continent,MinPrice,MaxPrice,Currency,Cuisine,Longitude,Latitude,PhoneNumber,Url,WebsiteUrl,Award,max_usd,price
0,D.O.M.,2021.0,"Rua BarÃ£o de Capanema 549, SÃ£o Paulo, 01411-...",SÃ£o Paulo,NaN,NaN,415,700.0,BRL,Creative,-46.667479,-23.566181,5.510000e+11,https://guide.michelin.com/en/sao-paulo-region...,http://www.domrestaurante.com.br/,2 MICHELIN Stars,139.677179,1
1,Ryo Gastronomia,2021.0,"Rua Pedroso Alvarenga 665, SÃ£o Paulo, 04531-0...",SÃ£o Paulo,NaN,NaN,160,650.0,BRL,Japanese,-46.676905,-23.581449,5.510000e+11,https://guide.michelin.com/en/sao-paulo-region...,https://www.ryogastronomia.com.br/,2 MICHELIN Stars,129.700238,1
2,Oteque,2021.0,"Rua Conde de IrajÃ¡ 581, Rio de Janeiro, 22271...",Rio de Janeiro,NaN,NaN,440,440.0,BRL,Modern Cuisine,-43.194424,-22.957470,5.520000e+11,https://guide.michelin.com/en/rio-de-janeiro-r...,https://www.oteque.com/,2 MICHELIN Stars,87.797084,1
3,Oro,2021.0,"Avenida General San Martin 889, Rio de Janeiro...",Rio de Janeiro,NaN,NaN,445,555.0,BRL,Creative,-43.224710,-22.986010,5.520000e+11,https://guide.michelin.com/en/rio-de-janeiro-r...,http://www.ororestaurante.com.br/,2 MICHELIN Stars,110.744049,1
4,Kinoshita,2021.0,"Rua Jacques FÃ©lix 405, SÃ£o Paulo, 04509-900,...",SÃ£o Paulo,NaN,NaN,83,383.0,BRL,Japanese,-46.671258,-23.591808,5.510000e+11,https://guide.michelin.com/en/sao-paulo-region...,https://www.restaurantekinoshita.com.br/,1 MICHELIN Star,76.423371,1

,Year,MaxPrice,Longitude,Latitude,PhoneNumber,max_usd
count,6375.0,6376.000000,6376.000000,6376.000000,6.268000e+03,6376.000000
mean,2021.0,3806.529172,25.357138,41.260683,3.035166e+11,117.049459
std,0.0,18276.349027,64.651813,11.818583,1.521174e+12,88.678572
min,2021.0,2.000000,-123.719444,-23.638434,4.977184e+07,0.601500
25%,2021.0,60.000000,0.649647,35.726995,3.314261e+10,53.851000
50%,2021.0,120.000000,7.269377,43.761822,3.531653e+10,91.616053
75%,2021.0,265.000000,19.052145,48.847792,8.522579e+10,157.827467
max,2021.0,380000.000000,139.847604,64.144365,4.980000e+13,1402.770525