In [7]:
import pandas as pd

In [8]:
df = pd.read_csv ('../data/michelin_reviews_full.csv')

In [9]:
df

      Unnamed: 0                                             review
0              0  Chef Barry Dindyal is the talent behind this p...
1              1  It may be the signature cry for falling object...
2              2  Once a pop-up and now a full-fledged brick-and...
3              3  Chef Rob Sonderman of the Federalist Pig has e...
4              4  This cozy Ethiopian den is an homage to Owner ...
...          ...                                                ...
1293        1293  The architecturally intriguing Hayden Tract di...
1294        1294  Set amidst the luxury shops of Rodeo Drive, th...
1295        1295  In contrast to its grand hotel setting, this b...
1296        1296  Every quarter of the year, Maude finds its new...
1297        1297  With a name that translates to "look at me," s...

[1298 rows x 2 columns]

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer(max_features=10_000,stop_words="english")
features = vec.fit_transform(df["review"])

print(features.shape) # (11314, 10000)

(1298, 10000)

In [12]:
from sklearn.neighbors import NearestNeighbors
knn = NearestNeighbors(n_neighbors=10, metric='cosine',n_jobs=-1)
knn.fit(features)

NearestNeighbors(metric='cosine', n_jobs=-1, n_neighbors=10)

In [13]:
philly_df = pd.read_csv('../data/infatuation_reviews.csv')

In [14]:
philly_df

                                                review
0    Most of the time, it’s fun to be right. It’s f...
1    When we’re in the mood for a creamy bowl of gr...
2    Jim’s is a retro, counter-service place on Sou...
3    You like Fork. Your boss likes Fork. Your neig...
4    Our review for this Israeli grill could probab...
..                                                 ...
558  Burg’s Hideaway is a small bar in Point Breeze...
559  If your date’s the type that does all of their...
560  No matter the weekend or the weather, Day by D...
561  There are mornings you feel invincible. You kn...
562  Scrolling through your stories the morning aft...

[563 rows x 1 columns]

In [15]:
philly_urls = pd.read_csv('../data/philly_infatuation_review_urls.csv')
philly_urls = philly_urls.drop_duplicates()
philly_urls = philly_urls.reset_index()
philly_urls = philly_urls.drop(['index'], axis=1)
philly_urls

                                                url
0                 /philadelphia/reviews/spice-finch
1      /philadelphia/reviews/bookers-restaurant-bar
2               /philadelphia/reviews/jims-south-st
3                        /philadelphia/reviews/fork
4                  /philadelphia/reviews/laser-wolf
..                                              ...
558     /philadelphia/reviews/burgs-hideaway-lounge
559        /philadelphia/reviews/pumpkin-restaurant
560                /philadelphia/reviews/day-by-day
561  /philadelphia/reviews/sams-morning-glory-diner
562                /philadelphia/reviews/nam-phuong

[563 rows x 1 columns]

In [16]:
merged_df = philly_df.merge(philly_urls, left_index=True, right_index=True)
merged_df

,review,url
0,"Most of the time, it’s fun to be right. It’s f...",/philadelphia/reviews/spice-finch
1,When we’re in the mood for a creamy bowl of gr...,/philadelphia/reviews/bookers-restaurant-bar
2,"Jim’s is a retro, counter-service place on Sou...",/philadelphia/reviews/jims-south-st
3,You like Fork. Your boss likes Fork. Your neig...,/philadelphia/reviews/fork
4,Our review for this Israeli grill could probab...,/philadelphia/reviews/laser-wolf
...,...,...
558,Burg’s Hideaway is a small bar in Point Breeze...,/philadelphia/reviews/burgs-hideaway-lounge
559,If your date’s the type that does all of their...,/philadelphia/reviews/pumpkin-restaurant
560,"No matter the weekend or the weather, Day by D...",/philadelphia/reviews/day-by-day
561,There are mornings you feel invincible. You kn...,/philadelphia/reviews/sams-morning-glory-diner
562,Scrolling through your stories the morning aft...,/philadelphia/reviews/nam-phuong

In [17]:
input_texts = merged_df['review']
input_features = vec.transform(input_texts)

distance = []
neighbor = []

D, N = knn.kneighbors(input_features, n_neighbors=1, return_distance=True)

for input_text, distances, neighbors in zip(input_texts, D, N):
    for dist, neighbor_idx in zip(distances, neighbors):
        distance.append(dist)
        neighbor.append(neighbor_idx)

In [18]:
distance

[0.8599846264118738,
 0.8858679432058156,
 0.8742767931650804,
 0.8978447230325738,
 0.8821166261527997,
 0.8391636145247933,
 0.9044894713280516,
 0.8585608694925002,
 0.8803052741169259,
 0.8591542506743906,
 0.8658387458913352,
 0.8520173857070603,
 0.8438852464687024,
 0.8717453535790296,
 0.8212567853462588,
 0.906365022437209,
 0.8709764089319121,
 0.8506142100893576,
 0.8851308970572703,
 0.8623983756188365,
 0.8538439552733148,
 0.8960802560264448,
 0.8709606600963861,
 0.8021675112109068,
 0.9178628117627925,
 0.8883474612748476,
 0.9028272757149957,
 0.7907393459093587,
 0.9017684312898598,
 0.8597694825674516,
 0.8772632814703722,
 0.8886910297599686,
 0.8115319313455112,
 0.852758185839961,
 0.8442757404175192,
 0.8328801576774376,
 0.839581011982404,
 0.7798597955280853,
 0.8820821108964141,
 0.9039868949634984,
 0.9004082622920531,
 0.8836787146948804,
 0.9109777799270106,
 0.8413478465708581,
 0.9079879763705873,
 0.893303601968068,
 0.8345923001313624,
 0.8914909677295656,
 0.9198148875521598,
 0.9091569746630929,
 0.8849262159218112,
 0.8755699948718524,
 0.921346560801052,
 0.8872139369107102,
 0.8582652427318427,
 0.8617633116732566,
 0.8423113315268916,
 0.8644962583440374,
 0.858729058777355,
 0.8908876909990657,
 0.7623256662670236,
 0.7593830489761586,
 0.7789560852177221,
 0.8764332485796893,
 0.8825142821097252,
 0.9020997049976194,
 0.8777342004906914,
 0.8958149152684219,
 0.8551176571031484,
 0.8535492917684632,
 0.9025548522846141,
 0.8590902855308664,
 0.8742249693414285,
 0.8553547504219395,
 0.8486355043105154,
 0.8143977844484362,
 0.8841215362113314,
 0.8692185289769141,
 0.8911621926062722,
 0.8609096790989383,
 0.8239382744152499,
 0.8975956832560276,
 0.8664991142363729,
 0.6801767783494971,
 0.8585679167284221,
 0.9033866728913152,
 0.8743308103266745,
 0.8869337068508989,
 0.8784306584900061,
 0.9058779271912215,
 0.9034595518377203,
 0.8535212501511606,
 0.8617170162670891,
 0.8487518976874777,
 0.8100979384898448,
 0.8975652623689889,
 0.8224823484167927,
 0.8613629128914707,
 0.8375043631104897,
 0.8768866222851017,
 0.8762536071410959,
 0.8696428919582149,
 0.8784616879563447,
 0.8861048092579378,
 0.9008535126837377,
 0.8626050560296973,
 0.8664857542121035,
 0.8772922690895016,
 0.8883582498494207,
 0.831602411630967,
 0.8800454828452485,
 0.7906603566610505,
 0.8702582973113303,
 0.8721874541976449,
 0.8846480784691354,
 0.9020177276140798,
 0.8735285363894005,
 0.8180746781149659,
 0.8315042807590033,
 0.839528781986802,
 0.8398321071445234,
 0.8815681658686314,
 0.8892918713662255,
 0.8698338145063123,
 0.8402042797243828,
 0.9114675387884217,
 0.844816989098801,
 0.8553657094131646,
 0.8442663386323831,
 0.8187910361310984,
 0.8618152099918082,
 0.9015910196711572,
 0.8961039532451763,
 0.8782550178512123,
 0.8970314389580842,
 0.8938054461202161,
 0.8789301240852829,
 0.8500106164316172,
 0.823559716496427,
 0.8979453569402052,
 0.8526637844412481,
 0.83720570212937,
 0.8748664091180957,
 0.8959781818275683,
 0.8954370838770499,
 0.8324623862617682,
 0.8786697245357339,
 0.9167240947667444,
 0.8947077137785338,
 0.8887189462130782,
 0.8347979503584673,
 0.9019996875177745,
 0.8752365529916653,
 0.8712536891420081,
 0.8855654047983486,
 0.9024224744403075,
 0.8921937414385025,
 0.9126176957986238,
 0.87919751142914,
 0.9163256620286868,
 0.8619499364027039,
 0.817236098853519,
 0.8761963023879933,
 0.9023512118328587,
 0.8616751096300632,
 0.9166536041841307,
 0.8575151946047948,
 0.8889541424395839,
 0.8850933681914158,
 0.8465559152229066,
 0.8481574431373912,
 0.8554033365495002,
 0.8974594135204508,
 0.8518290275261394,
 0.8942489213799394,
 0.8290891248948067,
 0.9001271290484225,
 0.8705999965943366,
 0.8841606099678287,
 0.8520451353384055,
 0.841756358867735,
 0.8870280428091741,
 0.912236349083273,
 0.8549602547770817,
 0.8743359018739965,
 0.8592207848791662,
 0.809116887017674,
 0.8526116785010691,
 0.8791738896158531,
 0.8663243133053328,
 0.8191527567692798,
 0.8450105063959606,
 0.8772708391575699,
 0.8853727141009486,
 0.8877912860065229,
 0.9001402435740563,
 0.8669974156073522,
 0.8744350805345809,
 0.8754792302169396,
 0.9093095591061322,
 0.8887232133651339,
 0.8994537410791326,
 0.8801205413522389,
 0.8877281608071957,
 0.8937354883406988,
 0.9069738262537191,
 0.8880457470759018,
 0.9026280299517089,
 0.877816855777418,
 0.8787123776565067,
 0.7515739872701771,
 0.8860603349626266,
 0.8962454477770295,
 0.8901809052571795,
 0.8955260375838736,
 0.8924729211741654,
 0.8846543514690689,
 0.8719452345392545,
 0.891893686078831,
 0.856495735328366,
 0.853518381484366,
 0.8219890078236429,
 0.8951733529480801,
 0.8474379455222718,
 0.8711459187163277,
 0.8857024312554137,
 0.8727861628857727,
 0.887871312778088,
 0.886931503023685,
 0.871263532738755,
 0.8529312674924763,
 0.8978361526534888,
 0.8580529211126462,
 0.7827929389828138,
 0.889121875007056,
 0.883383032180507,
 0.8708935435203463,
 0.8923569597721382,
 0.8303143895003904,
 0.8491519788306886,
 0.9071826036167661,
 0.8761476058675945,
 0.9065350840396946,
 0.8978325000959316,
 0.8950475861310897,
 0.8588157133955864,
 0.8827360718003778,
 0.9013573001922697,
 0.9178854499061866,
 0.9054267180461727,
 0.8680367575985386,
 0.8904841284591831,
 0.8180553900127592,
 0.8359566254330509,
 0.8433270012779879,
 0.9094743081253349,
 0.9206587299230018,
 0.8693449236768963,
 0.8789347975101275,
 0.906519645891482,
 0.8502163128019765,
 0.8634958150987393,
 0.8849403797508392,
 0.6185485901066439,
 0.8790562312670708,
 0.8791373125566964,
 0.8623363047465143,
 0.8564541145913857,
 0.8531430747034119,
 0.753031329095523,
 0.8523331441865549,
 0.8971565127501053,
 0.8878241853995044,
 0.8870461602768539,
 0.8920012567998553,
 0.8904444015397754,
 0.8545378976829738,
 0.8764105431257242,
 0.8671271492200926,
 0.9184801852847283,
 0.8600773500069648,
 0.8767258041878668,
 0.9148156549721594,
 0.8777249180315612,
 0.9038095396011945,
 0.8678080669375567,
 0.8913557658242455,
 0.8669836737089274,
 0.8899238939917842,
 0.7613270173742988,
 0.8661984159336357,
 0.8686387601540293,
 0.8853385174947095,
 0.8661043174618686,
 0.85140729140486,
 0.8248045727106064,
 0.8881391139157201,
 0.8932609175481129,
 0.8485422270310317,
 0.8552633578484374,
 0.8828923789834564,
 0.9132927453279369,
 0.8881213781693189,
 0.7781240776653733,
 0.8521160403982344,
 0.9031699960325917,
 0.8764767091993791,
 0.8732536593099602,
 0.8915038771713455,
 0.8820082628749691,
 0.8972320892363056,
 0.8539267574230118,
 0.82852141089602,
 0.8597572454363489,
 0.819022908429311,
 0.8241543420838376,
 0.8870445609850279,
 0.7768155437234033,
 0.881927653964879,
 0.878985250330599,
 0.8725635007516583,
 0.8425659148136341,
 0.8872825712962126,
 0.8420044776447242,
 0.8110885741725662,
 0.887605479731671,
 0.8562740975547943,
 0.8742497675099858,
 0.8861066594611272,
 0.8995742361559536,
 0.9110555376134182,
 0.8630819182050548,
 0.8917541496342257,
 0.8847808755602484,
 0.8680271596362739,
 0.8469105441105409,
 0.8594417962981821,
 0.8859332680446749,
 0.8868460946143246,
 0.8618863285122171,
 0.8948611069127304,
 0.8537637004452848,
 0.8311907224298909,
 0.8804019918339331,
 0.8773909812015205,
 0.9110629126586867,
 0.8621518139706648,
 0.8790144682823265,
 0.9030487934127537,
 0.8784695076321125,
 0.7887122860436213,
 0.8570338035490638,
 0.8969505055886372,
 0.8306421513633572,
 0.8998489000448637,
 0.8295769789754736,
 0.8986234744983864,
 0.876807639678688,
 0.8368363464666623,
 0.8805045149856596,
 0.8749266947792297,
 0.827261027971825,
 0.9099541823279242,
 0.9029164072436335,
 0.7844032829014183,
 0.8897140759096551,
 0.8923502677097837,
 0.9111179967780736,
 0.874396701792721,
 0.877679471930269,
 0.8894122439405598,
 0.9157643018793026,
 0.8863106894737894,
 0.8400304180857603,
 0.87387561813973,
 0.8842891803701536,
 0.8891217752435082,
 0.8899215728426797,
 0.7916893176173128,
 0.8686973361113364,
 0.8302575619139402,
 0.8862054011776674,
 0.8054665509192458,
 0.8888869660722533,
 0.9192223099546979,
 0.9012787610381092,
 0.9181453013429729,
 0.8813505449181639,
 0.8747271077272167,
 0.8952467567113902,
 0.8877277927531226,
 0.9130577984503191,
 0.915451214737672,
 0.895565366516254,
 0.8794420207947619,
 0.8751009404404889,
 0.8703786930566828,
 0.8987890782866637,
 0.8983112342674487,
 0.866262165065145,
 0.8967888419525863,
 0.8482823652037115,
 0.9003377097467814,
 0.883348872973693,
 0.8862945481559484,
 0.9011056468369871,
 0.8550328878334102,
 0.8741102218877693,
 0.8110470867550323,
 0.8908228571793052,
 0.8664731187157982,
 0.9019080586685927,
 0.881986928468055,
 0.8639048050307105,
 0.888185091941206,
 0.8669359891183726,
 0.8809718268851392,
 0.8954637992329203,
 0.9040676931863816,
 0.9184079792330321,
 0.8733227709772448,
 0.8990332407586072,
 0.8989641062368536,
 0.8404593120676366,
 0.8881356961955239,
 0.8137224540974557,
 0.8673686406960592,
 0.9044880233219292,
 0.8823997712541953,
 0.8789321584121735,
 0.9026250782989548,
 0.9029594553526636,
 0.912044343045492,
 0.8974495310654684,
 0.8953129220932254,
 0.9052713733633239,
 0.9148611564494205,
 0.8888913785024438,
 0.8867934945217577,
 0.9006102427315158,
 0.8973644693742948,
 0.8794350518271684,
 0.8307424355020904,
 0.8836013806869768,
 0.9135766896867604,
 0.9087977193830286,
 0.8816546638549528,
 0.847667619370934,
 0.8779504378834992,
 0.8859507709780838,
 0.9154558185344112,
 0.8535383051526435,
 0.9196533832800836,
 0.8956684892022946,
 0.8892679367612144,
 0.8821715454347625,
 0.8779923771095337,
 0.9101523882283091,
 0.8954866441749452,
 0.8737392346458672,
 0.8203597166655695,
 0.8970597699854821,
 0.8866256371155403,
 0.8988673490703363,
 0.9014043976869307,
 0.8978044789020553,
 0.9047200833999766,
 0.9051794158383649,
 0.8760378583940075,
 0.8539755994086731,
 0.9020539376528212,
 0.8736181387254907,
 0.9055219119592275,
 0.8742854407899457,
 0.7529657218742952,
 0.8936074936388769,
 0.8438711000506474,
 0.8637962279682284,
 0.8388274875707689,
 0.8868524401514943,
 0.8560865073773007,
 0.878427714097115,
 0.8989443235516204,
 0.8978385531312779,
 0.8823809483959333,
 0.8725940009724329,
 0.8961536724688096,
 0.9236471001693175,
 0.8978951509262921,
 0.7604373395951303,
 0.8787480079320359,
 0.8881364315648124,
 0.8812269795214904,
 0.8795174590860965,
 0.8532232692242372,
 0.8915830228070022,
 0.8961273519148084,
 0.8894818234937782,
 0.8880303766587352,
 0.8380590703134413,
 0.8794549474962441,
 0.875618228217689,
 0.8229723864693861,
 0.8862058111149894,
 0.8442616727245461,
 0.8689017845421776,
 0.9146234306107558,
 0.8687924944656003,
 0.827165210033309,
 0.8789717161827311,
 0.9029354646993858,
 0.8747475438136196,
 0.8711784218271037,
 0.8971928229620537,
 0.875417836848957,
 0.8966632024004989,
 0.8863719644421454,
 0.8834025850541773,
 0.8469175018551213,
 0.9115918773151758,
 0.892190737217083,
 0.8976974588602058,
 0.8685209239706911,
 0.891273040745204,
 0.8655345272334647,
 0.8472754507253994,
 0.8981110294448889,
 0.8723158695265273,
 0.8901010392167579,
 0.88486346862904,
 0.8323598827691452,
 0.8796276219673994,
 0.8533575886183533,
 0.8971017479590538,
 0.8819335009690696,
 0.8961964178219538,
 0.8159255078523567,
 0.8755502815429123,
 0.874670173315563,
 0.8957513279456479,
 0.9003103030560275,
 0.838149867015863,
 0.9190262955531878,
 0.899222139328397,
 0.900821172765792,
 0.8577308694492867,
 0.881050797586642,
 0.891411889847224,
 0.8728146129980988,
 0.8582127259243741,
 0.8620859581659821,
 0.9285395431150683,
 0.8931988416160126,
 0.8914543844372366,
 0.843708947429814,
 0.901819187752944,
 0.8701233742366196,
 0.9143981967110669,
 0.8843063506663909,
 0.9071470631436034,
 0.8505043882430591,
 0.9038846225608207,
 0.8333009379417171]

In [19]:
merged_df['distance'] = distance

In [20]:
merged_df['neighbor'] = neighbor

In [21]:
merged_df.sort_values('distance')

,review,url,distance,neighbor
263,Hajimaru is a small BYOB ramen shop on Girard ...,/philadelphia/reviews/hajimaru,0.618549,444
83,When you finish ordering at Neighborhood Ramen...,/philadelphia/reviews/neighborhood-ramen,0.680177,444
210,"Pop-up Anchor Light, which operates out of the...",/philadelphia/reviews/anchor-light,0.751574,225
474,There are a few pho places in the city that ev...,/philadelphia/reviews/ngon-ngon,0.752966,844
269,20th Street Pizza is from the people behind po...,/philadelphia/reviews/20th-street-pizza,0.753031,1027
...,...,...,...,...
48,Apparently back in the 1700s when most of Old ...,/philadelphia/reviews/revolution-house,0.919815,746
256,"Philadelphia Brewing Company has a 38,000-squa...",/philadelphia/reviews/philadelphia-brewing-com...,0.920659,943
52,Tradesman’s is part BBQ restaurant and part sp...,/philadelphia/reviews/tradesmans,0.921347,1274
487,Everything about The Library Bar in The Ritten...,/philadelphia/reviews/the-library-at-rittenhouse,0.923647,469
551,When your best friend is celebrating her dog’s...,/philadelphia/reviews/cake-life,0.928540,659

In [16]:
merged_df.to_csv('../data/distance_classified.csv', index=False, encoding='utf-8')